[gcp_service_account]
type = "service_account"
project_id = "control-procesos-510021"
private_key_id = "aafa643ccb5578aabb4e3747a39c0fa95cac451a"
private_key = "-----BEGIN PRIVATE KEY-----\nINGRESA_TU_NUEVA_CLAVE_AQUI\n-----END PRIVATE KEY-----\n"
client_email = "control-procesos@control-procesos-510021.iam.gserviceaccount.com"
client_id = "110338130362201619109"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/control-procesos%40control-procesos-510021.iam.gserviceaccount.com"
